[build]
builder = "nixpacks"

[deploy]
startCommand = "dotnet WASD.QLicPlatform.API/WASD.QLicPlatform.API.dll"
healthcheckPath = "/swagger"

[[services]]
name = "web"
sourcePath = "WASD.QLicPlatform.API"